export const SMALL_DOWN = "(max-width: 639px)"
export const MEDIUM_DOWN = "(max-width: 1024px)"
export const MEDIUM = "(min-width: 640px) and (max-width: 1024px)"
export const MEDIUM_UP = "(min-width: 640px)"
export const LARGE_UP = "(min-width: 1025px)"
export const X_LARGE_UP = "(min-width: 1440px)"
